version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache_transfer
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html
    networks:
      - entorno-web
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: bbdd_transfer
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=database 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
    networks:
      - entorno-web
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_transfer
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    networks:
      - entorno-web

networks:
  entorno-web:

volumes:
  mysql_data:

